#!/bin/bash

DICOM_PATH=""
INFO_PATH=""
EXTRA_ARGS=()

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -d|--dicom_folder)
      DICOM_PATH="$2"
      shift 2
      ;;
    -o|--info_folder)
      INFO_PATH="$2"
      shift 2
      ;;
    *)
      EXTRA_ARGS+=("$1")
      shift
      ;;
  esac
done

if [[ -z "$DICOM_PATH" || -z "$INFO_PATH" ]]; then
  echo "Error: Missing required arguments. Ensure you provide -d (DICOM folder) and -o (info folder)."
  exit 1
fi

echo "Running: sudo docker run --rm --net=host -v $DICOM_PATH:/dicom -v $INFO_PATH:/info pacsifier:1.0.0.dev0 pacsifier-move-csv ${EXTRA_ARGS[*]}"

sudo docker run --rm --net=host \
  -v "$DICOM_PATH:/dicom" \
  -v "$INFO_PATH:/info" \
  pacsifier:1.0.0.dev0 pacsifier-move-csv "${EXTRA_ARGS[@]}"
